#cloud-config
%{ if length(ssh_keys) > 0 }
ssh_authorized_keys:
%{ for ssh_key in ssh_keys }
- ${ssh_key}
%{ endfor }
%{ endif }
runcmd:
  - apt-get update
  - apt-get install -y apt-transport-https software-properties-common curl ca-certificates gnupg lsb-release linux-modules-extra-$(uname -r)
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update
  - apt-get -y install docker-ce docker-ce-cli containerd.io
  - modprobe -v ip_vs_lc
  - echo 'ip_vs_lc' > /etc/modules-load.d/ip_vs_lc.conf
  %{ if length(extra_cmds) > 0 }
  %{ for cmd in extra_cmds }
  - ${cmd}
  %{ endfor }
  %{ endif }
  - ${registration_command} --internal-address $(curl -s http://instance-data/latest/meta-data/local-ipv4)
